const Design = [
    {
      id: 1,
      name: "Atharva Admane",
      position: "Design Lead",
      image: "https://i.ibb.co/7Cx4kLy/atharva.jpg",
      alt: "Lead_Image",
      col: 3,
      linkedin: "",
      instagram: "https://instagram.com/atharva.1426?igshid=MzRlODBiNWFlZA",
      github: "",
      link: "",
    },
    {
      id: 2,
      name: "Aditya Nimbalkar",
      position: "Design Member",
      image: "https://i.ibb.co/xGmZ2B2/IMG20221211075037-Aditya-Adiii.jpg",
      alt: "Member_Image",
      col: 3,
      linkedin: "",
      instagram: "https://instagram.com/nottherealadi?igshid=MzRlODBiNWFlZA",
      github: "",
      link: "",
    },
    {
      id: 3,
      name: "Sankalp Bhirud",
      position: "Design Member",
      image: "https://i.ibb.co/bP3DZmr/sankalp.jpg",
      alt: "Member_Image",
      col: 3,
      linkedin: "",
      instagram: "https://instagram.com/sankalpbhirud?igshid=MzRlODBiNWFlZA",
      github: "",
      link: "",
    },
    {
      id: 4,
      name: "Neel Sawant",
      position: "Design Member",
      image: "https://i.ibb.co/Wz8n1FT/Photo-Retouch1691692371240-Neel-Sawant.jpg",
      alt: "Member_Image",
      col: 3,
      linkedin: "",
      instagram: "https://instagram.com/neel_sawant.11?igshid=MzRlODBiNWFlZA",
      github: "",
      link: "",
    },
    {
      id: 5,
      name: "Aryan Kadam",
      position: "Design Member",
      image: "https://i.ibb.co/gjT7bM4/Profile-Photo-Aryan-Kadam-page-0001.jpg",
      alt: "Member_Image",
      col: 3,
      linkedin: "",
      instagram: "https://instagram.com/rn_kadam_173?igshid=MzRlODBiNWFlZA",
      github: "",
      link: "",
    }
  ];
  
  export default Design;
  