const Design = [
    {
      id: 1,
      name: "Atharva Admane",
      position: "Design Lead",
      image: "https://i.ibb.co/7Cx4kLy/atharva.jpg",
      alt: "Lead_Image",
      col: 4,
      linkedin: "https://www.linkedin.com/in/atharva-admane-012560201",
      instagram: "https://instagram.com/atharva.1426",
      github: "",
      link: "",
    },
    {
      id: 2,
      name: "Aditya Nimbalkar",
      position: "Design Member",
      image: "https://i.ibb.co/xGmZ2B2/IMG20221211075037-Aditya-Adiii.jpg",
      alt: "Member_Image",
      col: 4,
      linkedin: "https://www.linkedin.com/in/aditya-nimbalkar-professional/",
      instagram: "https://instagram.com/nottherealadi",
      github: "",
	  googleCloud: "https://www.cloudskillsboost.google/public_profiles/a74efe1e-6cdb-4b43-9713-1e98e57438b7",
      link: "",
    },
    {
      id: 3,
      name: "Sankalp Bhirud",
      position: "Design Member",
      image: "https://i.ibb.co/bP3DZmr/sankalp.jpg",
      alt: "Member_Image",
      col: 4,
      linkedin: "https://www.linkedin.com/in/sankalp-bhirud-557799250/",
      instagram: "https://instagram.com/sankalpbhirud",
      github: "",
      link: "",
    },
    {
      id: 4,
      name: "Neel Sawant",
      position: "Design Member",
      image: "https://i.ibb.co/Wz8n1FT/Photo-Retouch1691692371240-Neel-Sawant.jpg",
      alt: "Member_Image",
      col: 5,
      linkedin: "https://www.linkedin.com/in/neel-sawant-a5a10a259",
      instagram: "https://instagram.com/neel_sawant.11",
      github: "https://github.com/Neels11",
      link: "",
    },
    {
      id: 5,
      name: "Aryan Kadam",
      position: "Design Member",
      image: "https://i.ibb.co/gjT7bM4/Profile-Photo-Aryan-Kadam-page-0001.jpg",
      alt: "Member_Image",
      col: 5,
      linkedin: "https://www.linkedin.com/in/aryan-kadam-b883041ba",
      instagram: "https://instagram.com/rn_kadam_173",
      github: "https://github.com/RnKadam?tab=overview&from=2023-07-01&to=2023-07-31",
      link: "",
    }
  ];
  
  export default Design;
  