const Web = [
  {
    id: 1,
    name: "Kamna Bhadoriya",
    position: "Web Development Lead",
    image: "https://i.ibb.co/b2FwqqM/profile-pic-12.png",
    alt: "Lead_Image",
    col: 4,
    linkedin: "https://www.linkedin.com/in/kamna-bhadoriya-05597b24a/",
    instagram: "https://www.instagram.com/kamna_bhadoriya/",
    github: "https://github.com/Kamna16",
    link: "",
  },
  {
    id: 2,
    name: "Shriya Sawashe",
    position: "Web Development Member",
    image: "https://i.ibb.co/FHKQH7D/profile-pic-29.png",
    alt: "Member_Image",
    col: 4,
    linkedin: "https://www.linkedin.com/in/shriya-s-81260a251",
    instagram: "https://instagram.com/shriya.125",
    github: "https://github.com/Shriya125",
    link: "",
  },
  {
    id: 3,
    name: "Prashant Patil",
    position: "Web Development Member",
    image: "https://i.ibb.co/5nCJmzJ/profile-pic-9.png",
    alt: "Member_Image",
    col: 4,
    linkedin: "https://www.linkedin.com/in/prashant-patil-918557225/",
    instagram: "",
    github: "https://github.com/PrashantPatil10178",
    link: "https://pixelenchanter.com/",
  },
];

export default Web;
