const workshops = [
  {
    id: 11,
    name: "Blockchain Untangled",
    date: "2022-03-19",
    dateAlt: "19th March 2022",
    day: "Saturday",
    about: "A blockchain is a distributed database that is shared among the nodes of a computer network. Blockchains are best known for their crucial role in cryptocurrency systems, such as Bitcoin. We are organizing this event to help you understand how blockchain can be used to make supply-chain system more efficient and improve its security. In this session, you will learn to:  - Explain how blockchain enables trust and business processes between participants - Evaluate when to use blockchain for a solution",
    speaker: "Shriniwas Khond Blockchain Developer Intern, Seracle and Krishna Waske, Software Developer Intern, AyanWorks",
    eventLink: "https://gdsc.community.dev/events/details/developer-student-clubs-aissms-institute-of-information-technology-pune-presents-blockchain-untangled/",
    imageSrc: "https://res.cloudinary.com/startup-grind/image/upload/c_fill,dpr_2,f_auto,g_center,q_auto:good/v1/gcs/platform-data-dsc/event_banners/launchpresso-h5iazR-wljU-unsplash.jpg",
    dataAos: "fade-up",
  },
  {
    id: 10,
    name: "Flutter Festival",
    date: "2022-03-18",
    dateAlt: "18th March 2022",
    day: "Friday",
    about: "In this event, we'll be learning about APIs and how APIs can be used to make our lives much easier. We'll be seeing how APIs can be integrated into Flutter and we'll be working with one very interesting API which will get us our favorite movies and TV Shows!! See you there!",
    speaker: "Parth Desai, Flutter Developer Intern, AmazeYoo",
    eventLink: "https://gdsc.community.dev/events/details/developer-student-clubs-aissms-institute-of-information-technology-pune-presents-flutter-festival-aissms-institute-of-information-technology-pune-4/",
    imageSrc: "https://res.cloudinary.com/startup-grind/image/upload/c_fill,dpr_2.0,f_auto,g_center,h_500,q_auto:good,w_500/v1/gcs/platform-data-dsc/events/FlutterFestival_Thumbnail_Dark_1080x1080_xeb9O7k.jpg",
    dataAos: "fade-left",
  },
  {
    id: 9,
    name: "Flutter Festival",
    date: "2022-03-15",
    dateAlt: "15th March 2022",
    day: "Tuesday",
    about: "In this session, we'll be going through the basics of Firebase and how it can be integrated with our Flutter app. Firebase is a Google provided Cloud service which makes you not worry about the backend of your app. May it be authentication or database or even hosting, Firebase got you covered!! Connect to Firebase and your app will be online instantly!! Join to learn more about Firebase!",
    speaker: "Parth Desai, Flutter Developer Intern, AmazeYoo",
    eventLink: "https://gdsc.community.dev/events/details/developer-student-clubs-aissms-institute-of-information-technology-pune-presents-flutter-festival-aissms-institute-of-information-technology-pune-3/",
    imageSrc: "https://res.cloudinary.com/startup-grind/image/upload/c_fill,dpr_2.0,f_auto,g_center,h_500,q_auto:good,w_500/v1/gcs/platform-data-dsc/events/FlutterFestival_Thumbnail_Dark_1080x1080_xeb9O7k.jpg",
    dataAos: "fade-right",
  },
  {
    id: 8,
    name: "Deep Learning - A walkthrough (Day 2)",
    date: "2022-03-13",
    dateAlt: "13th March 2022",
    day: "Sunday",
    about: "Artificial intelligence is one of the most emerging technological field. The large amount of data has given a boost to use AI products in different sectors of country. Be it ecommerce , healthcare , finance we can see that AI has leveraged the technology and has proven to be helping hand. 👩‍💻 Machine learning, Deep learning are one of the major aspects contributing for AI products. This workshop will introduce you to some of the important aspects and will also introduce you towards these fields. 🤖 So get ready to upskill yourselves!!🤩",
    speaker: "Aditya Gandhamal, Indian Army Intern",
    eventLink: "https://gdsc.community.dev/events/details/developer-student-clubs-aissms-institute-of-information-technology-pune-presents-deep-learning-a-walkthrough-day-2/",
    imageSrc: "https://i.ibb.co/JdbLp9t/ML-and-DL.jpg",
    dataAos: "fade-up",
  },
  {
    id: 7,
    name: "Machine Learning - A walkthrough (Day 1)",
    date: "2022-03-12",
    dateAlt: "12th March 2022",
    day: "Saturday",
    about: "Artificial intelligence is one of the most emerging technological field. The large amount of data has given a boost to use AI products in different sectors of country. Be it ecommerce , healthcare , finance we can see that AI has leveraged the technology and has proven to be helping hand. 👩‍💻 Machine learning, Deep learning are one of the major aspects contributing for AI products. This workshop will introduce you to some of the important aspects and will also introduce you towards these fields. 🤖 So get ready to upskill yourselves!!🤩",
    speaker: "Akshada Bhandari, Vasundharaa Geo Technologies Data Scientist Intern",
    eventLink: "https://gdsc.community.dev/events/details/developer-student-clubs-aissms-institute-of-information-technology-pune-presents-machine-learning-a-walkthrough-day-1/",
    imageSrc: "https://i.ibb.co/JdbLp9t/ML-and-DL.jpg",
    dataAos: "fade-left",
  },
  {
    id: 6,
    name: "Dive Into MERN Stack Web Development - Day 2",
    date: "2022-03-06",
    dateAlt: "6th March 2022",
    day: "Sunday",
    about: "Want to start your development journey and build some amazing projects that solve real-world problems?. GDSC AISSMS IOIT brings to you a hands-on workshop on MERN (Mongodb, Express.js, React.js, Node). MERN Stack is used for developing Full Stack Applications in fast and easy way💫. We are organizing this workshop in collaboration with renowned company REGex Software Services which will help you to understand how client and server side interact with each other and also to develop responsive and dynamic web applications🌀. We will be having a project which will provide you practical exposure of how all the designs, features and components of MERN Stack works🎯. So guys let's join us, we assure you that this workshop will definitely enhance your knowledge about Frontend and Backend Technologies 💯. Attend the workshop on - 📅- 5th and 6th Mar, 2022 🕔- 10:30 A.M.", 
    speaker: "",
    facilitator: "Ashish Patil",
    eventLink: "https://gdsc.community.dev/events/details/developer-student-clubs-aissms-institute-of-information-technology-pune-presents-dive-into-mern-stack-web-development-day-2/",
    imageSrc: "https://i.ibb.co/f1MdKRK/MERN-Stack.jpg",
    dataAos: "fade-right",
  },
  {
    id: 5,
    name: "Dive Into MERN Stack Web Development - Day 1",
    date: "2022-03-05",
    dateAlt: "5th March 2022",
    day: "Tuesday",
    about: "Want to start your development journey and build some amazing projects that solve real-world problems?. GDSC AISSMS IOIT brings to you a hands-on workshop on MERN (Mongodb, Express.js, React.js, Node). MERN Stack is used for developing Full Stack Applications in fast and easy way💫. We are organizing this workshop in collaboration with renowned company REGex Software Services which will help you to understand how client and server side interact with each other and also to develop responsive and dynamic web applications🌀. We will be having a project which will provide you practical exposure of how all the designs, features and components of MERN Stack works🎯. So guys let's join us, we assure you that this workshop will definitely enhance your knowledge about Frontend and Backend Technologies 💯. Attend the workshop on - 📅- 5th and 6th Mar, 2022 🕔- 10:30 A.M.",
    speaker: "",
    facilitator: "Ashish Patil",
    eventLink: "https://gdsc.community.dev/events/details/developer-student-clubs-aissms-institute-of-information-technology-pune-presents-dive-into-mern-stack-web-development-day-1/",
    imageSrc: "https://i.ibb.co/f1MdKRK/MERN-Stack.jpg",
    dataAos: "fade-up",
  },
  {
    id: 4,
    name: "Flutter Festival",
    date: "2022-03-02",
    dateAlt: "2nd March 2022",
    day: "Wednesday",
    about: "In continuation of the Dart Essentials workshop, we'll use the data models which we built and turn them into apps using Flutter. We'll finally start seeing the results of our code onto the mobile screen!! We'll be going through all the Flutter basics including widgets, navigation and much more, so don't forget to RSVP and attend!!",
    speaker: "Parth Desai, Flutter Developer Intern, AmazeYoo",
    eventLink: "https://gdsc.community.dev/events/details/developer-student-clubs-aissms-institute-of-information-technology-pune-presents-flutter-festival-aissms-institute-of-information-technology-pune-2/",
    imageSrc: "https://i.ibb.co/TmKCD4Y/Flutter-Festivals-Day-2.jpg",
    dataAos: "fade-left",
  },
  {
    id: 3,
    name: "Flutter Festival",
    date: "2022-03-01",
    dateAlt: "1st March 2022",
    day: "Tuesday",
    about: "Want to embark on your Flutter Development Journey? Well, we've got you covered!! Join us for our Dart Essentials Workshop and learn everything about Dart that you need to know to start with Flutter. Dart is a client-optimized programming language for fast apps on any platform. The various features for dart include : 1. Dart is optimized for UI, so you'll be able to create beautiful applications in no time. 2. Dart has a productive development, which will get you wanting to do more and more. 3. Dart is fast on all platforms.",
    speaker: "Parth Desai, Flutter Developer Intern, AmazeYoo",
    eventLink: "https://gdsc.community.dev/events/details/developer-student-clubs-aissms-institute-of-information-technology-pune-presents-flutter-festival-aissms-institute-of-information-technology-pune-1/",
    imageSrc: "https://i.ibb.co/KXdW7QP/Flutter-Festivals-Day-1.jpg",
    dataAos: "fade-right",
  },
  {
    id: 2,
    name: "Heroku - Project To Production",
    date: "2021-09-28",
    dateAlt: "28th September 2021",
    day: "Tuesday",
    about: "Do you guys want to host your project? Come join us where we will be learning concepts like what is cloud, cloud computing, service models and how to deploy Django Project on Heroku.",
    speaker: "Ashish Patil, Web Lead, GDSC, AISSMS IOIT",
    eventLink: "",
    imageSrc: "https://i.ibb.co/ypvdTSy/Heroku-Workshop.png",
    dataAos: "fade-up",
  },
  {
    id: 1,
    name: "Git and Github Hands-on Workshop",
    date: "2021-09-27",
    dateAlt: "27th September 2021",
    day: "Monday",
    about: "Get yourself introduced to the world of open-source. Get familiar with basic Git terminology and Github interface in this hands-on workshop! This workshop is an add-on to Developer Hacks - 21.",
    speaker: "Aditya Gandhamal, Cloud Co-Lead and Prarthana Chandak, Lead, GDSC, AISSMS IOIT",
    eventLink: "",
    imageSrc: "https://i.ibb.co/BG1r00M/Git-Github-Workshop.png",
    dataAos: "fade-left",
  },
];

export default workshops;
