const Management = [
  {
    id: 1,
    name: "Prajyot Jagtap",
    position: "Management Lead",
    image: "https://i.ibb.co/mDnJywV/Prajyot-Jagtap.png",
    alt: "Lead_Image",
    col: 4,
    linkedin: "https://www.linkedin.com/in/kaustubha-khandagale-70b216233",
    instagram: "https://instagram.com/kaustubhakhandagale",
    github: "https://github.com/KAUSTUBHAKK",
    link: "",
  },
  {
    id: 2,
    name: "Aditi Gughe",
    position: "Management Co-Lead",
    image: "https://i.ibb.co/4shQMJn/Aditi-ghuge.png",
    alt: "Member_Image",
    col: 4,
    linkedin: "https://www.linkedin.com/in/harsh-meshram/",
    instagram: "https://instagram.com/_harshmeshram_",
    github: "https://github.com/harsh-meshram",
    twitter: "https://twitter.com/_harshmeshram_",
    link: "",
  },
  {
    id: 3,
    name: "Sanika Mali",
    position: "Management Member",
    image:
      "https://i.ibb.co/7ng4zbf/Whats-App-Image-2023-08-13-at-1-30-54-PM-Saurabh-Rai.jpg",
    alt: "Member_Image",
    col: 4,
    linkedin: "https://www.linkedin.com/in/saurabh-rai-6580b9283",
    instagram: "https://instagram.com/saurabhrai4657",
    github: "",
    link: "",
  },
  {
    id: 4,
    name: "Sahil Khatri",
    position: "Management Member",
    image:
      "https://i.ibb.co/7ng4zbf/Whats-App-Image-2023-08-13-at-1-30-54-PM-Saurabh-Rai.jpg",
    alt: "Member_Image",
    col: 4,
    linkedin: "https://www.linkedin.com/in/saurabh-rai-6580b9283",
    instagram: "https://instagram.com/saurabhrai4657",
    github: "",
    link: "",
  },
];

export default Management;
