const ML = [
  {
    id: 1,
    name: "Ayush Bhujbal",
    position: "ML Lead",
    image: "https://i.ibb.co/xHwyv9Z/Ayush-Bhujbal.png",
    alt: "Lead_Image",
    col: 5,
    linkedin: "https://www.linkedin.com/in/satviknalavade/",
    instagram: "",
    github: "https://github.com/SatvikNalavade",
    link: "",
  },
  {
    id: 2,
    name: "Sameer Kulkarni",
    position: "ML Co-Lead",
    image: "https://i.ibb.co/0KPySKD/Sameer-Kulkarni.png",
    alt: "Member_Image",
    col: 5,
    linkedin: "https://www.linkedin.com/in/aditya-raut-4a92631b4/",
    instagram: "https://instagram.com/_adityaraut21",
    github: "https://github.com/AdityaRaut21",
    link: "",
  },
  {
    id: 3,
    name: "Yash Potdar",
    position: "ML Co-Lead",
    image: "https://i.ibb.co/JptCgc9/profile-pic-7.png",
    alt: "Member_Image",
    col: 5,
    linkedin: "https://www.linkedin.com/in/aditya-raut-4a92631b4/",
    instagram: "https://instagram.com/_adityaraut21",
    github: "https://github.com/AdityaRaut21",
    link: "",
  },
];

export default ML;
