const Web = [
  {
    id: 1,
    name: "Ashwin Maurya",
    position: "Web Development Lead",
    image: "https://i.ibb.co/VVkJzyB/profile-pic-2.png",
    alt: "Lead_Image",
    col: 4,
    linkedin: "https://www.linkedin.com/in/kamna-bhadoriya-05597b24a/",
    instagram: "https://www.instagram.com/kamna_bhadoriya/",
    github: "https://github.com/Kamna16",
    link: "",
  },
  {
    id: 2,
    name: "Atharv Sonawane",
    position: "Web Development Co-Lead",
    image: "https://i.ibb.co/C7zc55X/profile-pic.png",
    alt: "Member_Image",
    col: 4,
    linkedin: "https://www.linkedin.com/in/shriya-s-81260a251",
    instagram: "https://instagram.com/shriya.125",
    github: "https://github.com/Shriya125",
    link: "",
  },
  {
    id: 3,
    name: "Harshal Parate",
    position: "Web Development Member",
    image: "https://i.ibb.co/7Q2rJ6x/Harshal-pathare.png",
    alt: "Member_Image",
    col: 4,
    linkedin: "https://www.linkedin.com/in/prashant-patil-918557225/",
    instagram: "",
    github: "https://github.com/PrashantPatil10178",
    link: "https://pixelenchanter.com/",
  },
  {
    id: 4,
    name: "Srinidhi Kulkarni",
    position: "Web Development Member",
    image: "https://i.ibb.co/kXzgHTX/profile-pic-10.png",
    alt: "Member_Image",
    col: 4,
    linkedin: "https://www.linkedin.com/in/prashant-patil-918557225/",
    instagram: "",
    github: "https://github.com/PrashantPatil10178",
    link: "https://pixelenchanter.com/",
  },
];

export default Web;
