const Management = [
  {
    id: 1,
    name: "Omkar Danave",
    position: "Management Lead",
    image: "https://i.ibb.co/wpc9D2Y/Omkar-Danave.png",
    alt: "Lead_Image",
    col: 4,
    linkedin: "https://www.linkedin.com/in/omdanave/",
    instagram: "https://www.instagram.com/__life.racer/",
    github: "https://github.com/omkardanave",
    link: "",
    profile: "https://gdsc.community.dev/u/mmjmtk/#/about",
    details: "Passionate learner. Self Motivated!, Enthusiastic about aquiring skills and gaining various experiences, Exploring the Tech-World. Food 😋 + Music🎵 = ❤️",
    tooltip: "management_tooltip"
  },
  {
    id: 2,
    name: "Krishna Waske",
    position: "Management Member",
    image: "https://i.ibb.co/wRgG5wr/Krishna-Waske.jpg",
    alt: "Member_Image",
    col: 4,
    linkedin: "https://www.linkedin.com/in/krishna-waske-329a99178",
    instagram: "https://www.instagram.com/waskekrishna/",
    github: "https://github.com/GHkrishna",
    link: "",
    profile: "https://gdsc.community.dev/u/mbq8ny/",
    details: "A curious human. Interested in decentralization by blockchain implementation.",
    tooltip: "management_tooltip"
  },
  {
    id: 3,
    name: "Shrusti Kharche",
    position: "Management Member",
    image: "https://i.ibb.co/YTyNmPX/Shrushti-Kharche.jpg",
    alt: "Member_Image",
    col: 4,
    linkedin: "https://www.linkedin.com/in/shrushti-kharche-2a85a1215",
    instagram: "https://www.instagram.com/_shrushti_k",
    github: "",
    link: "https://www.hackerrank.com/shrushtigk12",
    profile: "https://gdsc.community.dev/u/mb2z3c/",
    details: "I am Shrushti. Studing in second in the department of AI and DS branch. I am an enthusiastic, dependable and detail-oriented and I think positively. My hobbies are painting, reading, travelling.",
    tooltip: "management_tooltip"
  },
  {
    id: 4,
    name: "Sanyukta Kamble",
    position: "Social Media Lead",
    image: "https://i.ibb.co/f49wvHR/Sanyukta-kamble.jpg",
    alt: "Lead_Image",
    col: 6,
    linkedin: "https://www.linkedin.com/in/sanyukta-kamble-a158711a6",
    instagram: "https://www.instagram.com/of.sanyukta",
    github: "https://github.com/sanyukta111",
    link: "https://leetcode.com/sanyuktakamble4/",
    profile: "https://gdsc.community.dev/u/m48w4k/#/about",
    details: "I am a UX designer and also love contributing to society by technology. Apart from coding, I am also an avid reader and a part-time writer. I love doing new things and making the best memories out of it",
    tooltip: "cloud_ml_tooltip"
  },
  {
    id: 5,
    name: "Pornima Lokhande",
    position: "Design Lead",
    image: "https://i.ibb.co/PNrtZN4/Pornima-Lokhande.jpg",
    alt: "Lead_Image",
    col: 6,
    linkedin: "www.linkedin.com/in/pornima-lokhande-31b480200",
    instagram: "https://www.instagram.com/ponu234",
    github: "https://github.com/PornimaLokhande",
    link: "https://www.artstation.com/pornimalokhande0210",
    profile: "https://gdsc.community.dev/u/mp2p7m/",
    details: "I have been working as a freelance graphic and UI/UX designer since the moment I found coding boring ;). I have also cofounded a startup where I work as the lead designer.",
    tooltip: "cloud_ml_tooltip"
  },
];

export default Management;
