const Web = [
  {
    id: 1,
    name: "Kamna Bhadoriya",
    position: "Web Development Lead",
    image: "https://i.ibb.co/ZNXxkjC/my-photo.jpg",
    alt: "Lead_Image",
    col: 3,
    linkedin: "https://www.linkedin.com/in/ashish-patil-👨‍💻-ab2879192",
    instagram: "https://www.instagram.com/ashishpatil2831/",
    github: "https://github.com/Ashish2831",
    link: "",
  },
  {
    id: 2,
    name: "Shriya Sawashe",
    position: "Web Development Member",
    image: "https://i.ibb.co/3y5yK02/shriya-sawashe.jpg",
    alt: "Member_Image",
    col: 3,
    linkedin: "https://www.linkedin.com/in/sarangkulkarni99",
    instagram: "https://www.instagram.com/_sarang_kulkarni_",
    github: "https://github.com/sarangkulkarni99",
    link: "",
  },
  {
    id: 3,
    name: "Prashant Patil",
    position: "Web Development Member",
    image: "https://i.ibb.co/qsKPwTc/photo-1-Prashant-Patil.jpg",
    alt: "Member_Image",
    col: 3,
    linkedin: "https://www.linkedin.com/in/prakalp-pande-a56219220/",
    instagram: "https://www.instagram.com/prakalp_pande_/",
    github: "https://github.com/PRAKALP-PANDE",
    link: "",
  },
];

export default Web;
