const Web = [
  {
    id: 1,
    name: "Kamna Bhadoriya",
    position: "Web Development Lead",
    image: "https://i.ibb.co/ZNXxkjC/my-photo.jpg",
    alt: "Lead_Image",
    col: 3,
    linkedin: "",
    instagram: "",
    github: "",
    link: "",
  },
  {
    id: 2,
    name: "Shriya Sawashe",
    position: "Web Development Member",
    image: "https://i.ibb.co/3y5yK02/shriya-sawashe.jpg",
    alt: "Member_Image",
    col: 3,
    linkedin: "",
    instagram: "",
    github: "",
    link: "",
  },
  {
    id: 3,
    name: "Prashant Patil",
    position: "Web Development Member",
    image: "https://i.ibb.co/qsKPwTc/photo-1-Prashant-Patil.jpg",
    alt: "Member_Image",
    col: 3,
    linkedin: "",
    instagram: "",
    github: "",
    link: "",
  },
];

export default Web;
