const Web = [
  {
    id: 1,
    name: "Ashish Patil",
    position: "Web Development Lead",
    image: "https://i.ibb.co/qJGLmVz/Ashish-Patil-GDSC-Web.jpg",
    alt: "Lead_Image",
    col: 3,
    linkedin: "https://www.linkedin.com/in/ashish-patil-👨‍💻-ab2879192",
    instagram: "https://www.instagram.com/ashishpatil2831/",
    github: "https://github.com/Ashish2831",
    link: "https://www.codechef.com/users/ashish_28/",
    profile: "https://gdsc.community.dev/u/mw4r7j/#/about",
    details:
      "👨‍💻 Computer Science Major, My passion in this field brought me into an amazing journey where I learned different new skills and implemented in real life scenarios like developing Full Stack Apps especially using Python Django, MERN Stack, Heroku and AWS.",
    tooltip: "",
  },
  {
    id: 2,
    name: "Ganesh Birajdar",
    position: "Web Development Co-Lead",
    image: "https://i.ibb.co/t83qp1V/Ganesh-Birajdar.jpg",
    alt: "Co_Lead_Image",
    col: 3,
    linkedin: "https://www.linkedin.com/in/ganesh-birajdar-a3a959219",
    instagram: "https://www.instagram.com/ganeshb_009",
    github: "https://github.com/ganeshbirajdar09",
    link: "https://leetcode.com/ganeshb09/",
    profile: "https://gdsc.community.dev/u/mv5r3f/#/about",
    details:
      "Hi, I'm Ganesh Birajdar, A passionate Full-Stack Developer. I am well-versed with multiple web development technologies and I can help you build Web apps in MERN stack.",
    tooltip: "",
  },
  {
    id: 3,
    name: "Sarang Kulkarni",
    position: "Web Development Member",
    image: "https://i.ibb.co/TvZCL7s/Sarang-Kulkarni.jpg",
    alt: "Member_Image",
    col: 3,
    linkedin: "https://www.linkedin.com/in/sarangkulkarni99",
    instagram: "https://www.instagram.com/_sarang_kulkarni_",
    github: "https://github.com/sarangkulkarni99",
    link: "",
    profile: "https://gdsc.community.dev/u/mpmaz5/#/about",
    details:
      "Web Developer Member, Python enthusiast proficient with frontend and backend technologies.",
    tooltip: "",
  },
  {
    id: 4,
    name: "Prakalp Pande",
    position: "Web Development Member",
    image: "https://i.ibb.co/dL6FjFc/PRAKALP-PANDE.jpg",
    alt: "Member_Image",
    col: 3,
    linkedin: "https://www.linkedin.com/in/prakalp-pande-a56219220/",
    instagram: "https://www.instagram.com/prakalp_pande_/",
    github: "https://github.com/PRAKALP-PANDE",
    link: "https://www.hackerrank.com/prakalpsp16",
    profile: "https://gdsc.community.dev/u/mgyh47/#/about",
    details:
      "Hello, my name is Prakalp Pande. A Full-Stack Web-Developer. Experience in HTML, CSS, JavaScript, flask, Mongodb",
    tooltip: "",
  },
];

export default Web;
