const upcoming = [{
    id: 7,
    name: "Machine Learning - A walkthrough (Day 1)",
    date: "2022-03-12",
    dateAlt: "12th March 2022",
    day: "Saturday",
    about: "Artificial intelligence is one of the most emerging technological field. The large amount of data has given a boost to use AI products in different sectors of country. Be it ecommerce , healthcare , finance we can see that AI has leveraged the technology and has proven to be helping hand. 👩‍💻 Machine learning, Deep learning are one of the major aspects contributing for AI products. This workshop will introduce you to some of the important aspects and will also introduce you towards these fields. 🤖 So get ready to upskill yourselves!!🤩",
    speaker: "Akshada Bhandari, Vasundharaa Geo Technologies Data Scientist Intern",
    eventLink: "https://gdsc.community.dev/events/details/developer-student-clubs-aissms-institute-of-information-technology-pune-presents-machine-learning-a-walkthrough-day-1/",
    imageSrc: "https://www.wordstream.com/wp-content/uploads/2021/07/machine-learning1-1.png",
    dataAos: "fade-left",
  },
  {
    id: 6,
    name: "Dive Into MERN Stack Web Development - Day 2",
    date: "2022-03-06",
    dateAlt: "6th March 2022",
    day: "Sunday",
    about: "Want to start your development journey and build some amazing projects that solve real-world problems?. GDSC AISSMS IOIT brings to you a hands-on workshop on MERN (Mongodb, Express.js, React.js, Node). MERN Stack is used for developing Full Stack Applications in fast and easy way💫. We are organizing this workshop in collaboration with renowned company REGex Software Services which will help you to understand how client and server side interact with each other and also to develop responsive and dynamic web applications🌀. We will be having a project which will provide you practical exposure of how all the designs, features and components of MERN Stack works🎯. So guys let's join us, we assure you that this workshop will definitely enhance your knowledge about Frontend and Backend Technologies 💯. Attend the workshop on - 📅- 5th and 6th Mar, 2022 🕔- 10:30 A.M.",
    speaker: "",
    facilitator: "Ashish Patil",
    eventLink: "https://gdsc.community.dev/events/details/developer-student-clubs-aissms-institute-of-information-technology-pune-presents-dive-into-mern-stack-web-development-day-2/",
    imageSrc: "https://i.ibb.co/f1MdKRK/MERN-Stack.jpg",
    dataAos: "fade-right",
  },
  {
    id: 5,
    name: "Dive Into MERN Stack Web Development - Day 1",
    date: "2022-03-05",
    dateAlt: "5th March 2022",
    day: "Tuesday",
    about: "Want to start your development journey and build some amazing projects that solve real-world problems?. GDSC AISSMS IOIT brings to you a hands-on workshop on MERN (Mongodb, Express.js, React.js, Node). MERN Stack is used for developing Full Stack Applications in fast and easy way💫. We are organizing this workshop in collaboration with renowned company REGex Software Services which will help you to understand how client and server side interact with each other and also to develop responsive and dynamic web applications🌀. We will be having a project which will provide you practical exposure of how all the designs, features and components of MERN Stack works🎯. So guys let's join us, we assure you that this workshop will definitely enhance your knowledge about Frontend and Backend Technologies 💯. Attend the workshop on - 📅- 5th and 6th Mar, 2022 🕔- 10:30 A.M.",
    speaker: "",
    facilitator: "Ashish Patil",
    eventLink: "https://gdsc.community.dev/events/details/developer-student-clubs-aissms-institute-of-information-technology-pune-presents-dive-into-mern-stack-web-development-day-1/",
    imageSrc: "https://i.ibb.co/f1MdKRK/MERN-Stack.jpg",
    dataAos: "fade-up",
  }
];

export default upcoming;