const Android = [
  {
    id: 1,
    name: "Parth Desai",
    position: "Android Lead",
    image: "https://i.ibb.co/mv9bc5q/Parth-Desai.png",
    alt: "Lead_Image",
    col: 3,
    linkedin: "https://www.linkedin.com/in/parth-desai-021027",
    instagram: "https://www.instagram.com/redpaladin1001",
    github: "https://www.linkedin.com/in/parth-desai-021027",
    link: "",
    profile: "https://gdsc.community.dev/u/m477nk/#/about",
    details:
      "I have been working in Flutter and Firebase since the past 3 years and currently have a startup where we build apps and websites and a lot of cool stuff using flutter and dart.",
    tooltip: "",
  },
  {
    id: 2,
    name: "Prathamesh Chaudhari",
    position: "Android Co-Lead",
    image: "https://i.ibb.co/W32632j/PRATHMESH-CHAUDHARI.jpg",
    alt: "Co_Lead_Image",
    col: 3,
    linkedin: "https://www.linkedin.com/in/prathmeshchaudhari",
    instagram: "https://www.instagram.com/@prathmeshc_",
    github: "https://github.com/Retr094",
    link: "",
    profile: "https://gdsc.community.dev/u/mpht4a/",
    details:
      "I'm an aspiring Android Developer who wants to make a difference by developing applications that can make people's lives convenient and comfortable.",
    tooltip: "",
  },
  {
    id: 3,
    name: "Aniruddh Karekar",
    position: "Android Member",
    image: "https://i.ibb.co/0hdDhDq/Aniruddh-Karekar.png",
    alt: "Member_Image",
    col: 3,
    linkedin: "https://www.linkedin.com/in/aniruddh-karekar-5711531a4/",
    instagram: "",
    github: "",
    link: "https://leetcode.com/ani-codes-49/",
    profile: "https://gdsc.community.dev/u/m49myd",
    details:
      "Interested in software development. Curious about what I learn. Want to gain knowledge and experience about my interests.",
    tooltip: "",
  },
  {
    id: 4,
    name: "Het Bhalala",
    position: "Android Member",
    image: "https://i.ibb.co/WfJYrbK/IMG-3341.jpg",
    alt: "Member_Image",
    col: 3,
    linkedin: "https://www.linkedin.com/in/het-bhalala-38a979204",
    instagram: "https://www.instagram.com/hetbhalala11",
    github: "",
    link: "",
    profile: "",
    details: "Hi I’m Het Bhalala from SE Comp, I’m proud GDSC Android Member and  have a desire to learn emerging technology and adapt to changing environment.",
    tooltip: "",
  },
];

export default Android;
